### ISSUE TITLE
hat by id

### ISSUE THREAD

**Issue by Justsomeotakuu** [topitbopit/HatLib#1]
hello, i am pretty new to lua, but i was just wondering if there is a way to make a hat by using a hat id, i love your library by the way

**Comment by topitbopit** [comment]
There isn't a way currently, so I'll add it right now - thanks

**Comment by topitbopit** [comment]
Added `HatModule:CreateHatById`, which takes in a meshid

**Comment by Justsomeotakuu** [comment]
alright thanks!

> Added `HatModule:CreateHatById`, which takes in a meshid
